### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by MichaelDevC** [Lalit2005/staticshield#55]
Hi 👋, I saw this amazing project and tested it!
I want to contribute, but can you share the dev guidelines so I can edit and test locally/on Vercel some changes?
Like what ENV variables we need, how to setup the DB, etc...

I'm very interested in this project 😉, hope someone reply soon...

**Comment by Lalit2005** [comment]
Glad that you would like to contribute
Yeah sure, I'll add them really really soon 🙂
