### ISSUE TITLE
Javascript Enabed but I get error

### ISSUE THREAD

**Issue by iozcelik** [Lalit2005/staticshield#82]
In my browser javascript enabled. I check twice.
![image](https://user-images.githubusercontent.com/10682780/128169013-ee4e1af8-b7b0-4b87-8ed1-028ece02df1e.png)

However, I get this warning.
![image](https://user-images.githubusercontent.com/10682780/128169055-81d02ba8-f541-46d0-a7c5-59a0857e2208.png)

"Staticshield checks for the valid token, verifies it and redirects to login page using Javascript. All this is done by the script that is loaded externally. Please enable network requests in your browser."

I try to add this function in docusaurus.

**Comment by Lalit2005** [comment]
This seems like an issue with **Blocking of network requests**, not with executing javascript.

https://user-images.githubusercontent.com/69138026/128324269-95e2cc25-7a32-4da9-8e81-832512545c5d.mp4

In that video, you will be redirected to the _Request Blocked_ page only when the network requests are blocked for the `staticshield.vercel.app` domain

Can you give some steps to reproduce the issue? Or any example on CodeSandbox or StackBlitz would help too

**Comment by Lalit2005** [comment]
Hello @iozcelik, I've figured out the problem. There seems to be an issue with CORS with StaticShield. You will probably have to do nothing extra to get it working properly

I'll fix it as soon as possible.

**Comment by Lalit2005** [comment]
Fixed it 🎉 

If the problem persists, please reopen the issue
